# Generated by Django 5.0.1 on 2025-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', [('FIC_LIT', 'Literary Fiction'), ('FIC_MYS', 'Mystery'), ('FIC_THR', 'Thriller'), ('FIC_SFF', 'Science Fiction/Fantasy'), ('FIC_ROM', 'Romance'), ('FIC_HIS', 'Historical Fiction')]), ('Non-Fiction', [('NON_BIO', 'Biography/Memoir'), ('NON_HIS', 'History'), ('NON_SCI', 'Science'), ('NON_TECH', 'Technology'), ('NON_SELF', 'Self-Help'), ('NON_BUS', 'Business'), ('NON_PHIL', 'Philosophy')]), ('Other', [('OTH_POET', 'Poetry'), ('OTH_DRAMA', 'Drama'), ('OTH_COMIC', 'Comics/Graphic Novels'), ('OTH_CHILD', "Children's"), ('OTH_YA', 'Young Adult'), ('OTH_OTHER', 'Other')])], max_length=20),
        ),
    ]
